import {test} from 'node:test';
import assert from 'node:assert/strict';
import {scryptSync} from 'node:crypto';
import {createHandler as createLogin} from '../netlify/functions/login.mjs';
import {createHandler as createApi} from '../netlify/functions/api.mjs';
import {createHandler as createIngest} from '../netlify/functions/ingest.mjs';
import {digest,randomToken} from '../lib/security.mjs';
test('full session lifecycle and telemetry access separation',async()=>{
 const maps=new Map();const store=({name})=>{if(!maps.has(name))maps.set(name,new Map());const map=maps.get(name);return {get:async k=>map.get(k)||null,setJSON:async(k,v)=>map.set(k,v),delete:async k=>map.delete(k)};};
 const salt='1'.repeat(32);process.env.DASHBOARD_USERNAME='owner';process.env.DASHBOARD_PASSWORD_HASH=salt+':'+scryptSync('strong-test-password',salt,64,{N:32768,r:8,p:1,maxmem:67108864}).toString('hex');
 const key=randomToken();process.env.INGEST_KEY_HASH=digest(key);
 const login=createLogin(store),api=createApi(store),ingest=createIngest(store);
 const request=(path,method='GET',data,headers={})=>new Request('https://example.test/api/'+path,{method,headers:{origin:'https://example.test',...(data?{'content-type':'application/json'}:{}),...headers},...(data?{body:JSON.stringify(data)}:{})});
 assert.equal((await api(request('telemetry'))).status,401);
 assert.equal((await api(request('telemetry','GET',null,{authorization:'Bearer '+key}))).status,401);
 const response=await login(request('login','POST',{username:'owner',password:'strong-test-password',role:'admin'}));
 assert.equal(response.status,200);assert.equal((await response.json()).role,'viewer');
 const cookie=response.headers.get('set-cookie').split(';')[0];
 assert.equal((await api(request('session','GET',null,{cookie}))).status,200);
 assert.equal((await ingest(request('ingest','POST',{}, {cookie}))).status,401);
 const empty=await (await api(request('telemetry','GET',null,{cookie}))).json();assert.equal(empty.stale,true);assert.equal(empty.record,null);
 const payload={received_at:Date.now()/1000,retained:false,telemetry:{schema_version:1,device_id:'esp32-01',source:'hardware',boot_id:'1234567890abcdef',sequence:1,uptime_ms:10000,timestamp:null,sensor_online:true,sensor_map_verified:false,reference_online:true,pump_on:false,pump_fault:false,moisture_pct:0,soil_temp_c:27,ph:7,ec_us_cm:0,nitrogen_mg_kg:0,phosphorus_mg_kg:0,potassium_mg_kg:0,reference_temp_c:27.38}};
 assert.equal((await ingest(request('ingest','POST',payload,{authorization:'Bearer '+key}))).status,200);
 const fresh=await (await api(request('telemetry','GET',null,{cookie}))).json();assert.equal(fresh.stale,false);assert.equal(fresh.record.telemetry.ph,7);assert.equal(fresh.record.telemetry.reference_temp_c,27.38);
 assert.equal((await (await ingest(request('ingest','POST',payload,{authorization:'Bearer '+key}))).json()).ignored,true);
 maps.get('soilhealth-data').get('latest').received_at-=60;
 assert.equal((await (await api(request('telemetry','GET',null,{cookie}))).json()).stale,true);
 assert.equal((await api(request('logout','POST',null,{cookie,origin:'https://evil.test'}))).status,403);
 assert.equal((await api(request('logout','POST',null,{cookie}))).status,200);
 assert.equal((await api(request('telemetry','GET',null,{cookie}))).status,401);
});
